---
    environment: production
    chdir: /u/apps/gettingwasted/current
    address: 127.0.0.1
    user: mongrel
    group: mongrel
    port: 8500
    pid: pids/thin.pid
    rackup: config/config.ru
    log: log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true